### ISSUE TITLE
No Device or Entities returned

### ISSUE THREAD

**Issue by Chobnob** [DurgNomis-drol/ha_toyota#269]
Using V2.0.2 of the integration stopped returning any values all showing entities as unavailable. Following a complete removal of the integration and an upgrade to V2.0.3 created an "Integration entry" without any "Devices" or "Entities". HA version was 2024.5.4 upgraded to 2024.6.2 with the same issue. This is based on the latest My Toyota app and a Rav4 PHEV.

![HA toyota](https://github.com/DurgNomis-drol/ha_toyota/assets/140966764/7f8ef771-61ce-49c9-93f9-c23e69c0d4da)

The log error message after the installation is 

Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:366
integration: Device tracker (documentation, issues)
First occurred: 8:00:58 AM (2 occurrences)
Last logged: 8:21:07 AM

Error while setting up toyota platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/toyota/device_tracker.py", line 39, in async_setup_entry
    for index, vehicle in enumerate(coordinator.data)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

ALSO

This error originated from a custom integration.

Logger: custom_components.toyota
Source: custom_components/toyota/__init__.py:112
integration: Toyota Connected Services (documentation, issues)
First occurred: June 13, 2024 at 6:09:21 PM (3 occurrences)
Last logged: 6:19:04 AM

1 validation error for ElectricResponseModel payload -> evRangeWithAc field required (type=value_error.missing)

**Comment by CM000n** [comment]
Closed due to discontinuation of the project. See: https://github.com/DurgNomis-drol/ha_toyota/issues/346
