### ISSUE TITLE
Fuel level sensor not available

### ISSUE THREAD

**Issue by desosav** [DurgNomis-drol/ha_toyota#273]
It stopped working a few days ago. 

```
> 2024-06-28 08:45:12.509 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity None for domain sensor with platform toyota
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
>     await coro
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 831, in _async_add_entity
>     unit_of_measurement=entity.unit_of_measurement,
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 512, in unit_of_measurement
>     if self._is_valid_suggested_unit(suggested_unit_of_measurement):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 383, in _is_valid_suggested_unit
>     raise ValueError(
> ValueError: Entity <class 'custom_components.toyota.sensor.ToyotaSensor'> suggest an incorrect unit of measurement: %.
```

**Comment by Stemmi90** [comment]
Same kind of issue when updated to 2024.7.0 so restored back to 2024.6.4

**Comment by Anangaranga** [comment]
Same here...🫤

**Comment by desosav** [comment]
this is a workaround for anyone interested in updating HA core to the latest available release, while keeping the fuel level sensor enabled.
I have updated line 230 in /homeassistant/custom_components/toyota/sensor.py file (replace PERCENTAGE with None) 
Now the fuel level is working but obviously no unit of measurement is assigned to the sensor. I am not a programmer, so this is just a workaround until this is resolved by the ha_toyota integration devs.

`vehicle._vehicle_info.extended_capabilities.fuel_level_available,
FUEL_LEVEL_ENTITY_DESCRIPTION,
ToyotaSensor,
None,`

**Comment by nisu66** [comment]
same error from update 2024.7

**Comment by mario-pranjic** [comment]
Same here. I upgraded directly from 2024.6.x (latest) to 2024.7.3 and fuel level sensor is off.
MyToyota app shows that information properly.

**Comment by mario-pranjic** [comment]
> this is a workaround for anyone interested in updating HA core to the latest available release, while keeping the fuel level sensor enabled. I have updated line 230 in /homeassistant/custom_components/toyota/sensor.py file (replace PERCENTAGE with None) Now the fuel level is working but obviously no unit of measurement is assigned to the sensor. I am not a programmer, so this is just a workaround until this is resolved by the ha_toyota integration devs.
> 
> `vehicle._vehicle_info.extended_capabilities.fuel_level_available, FUEL_LEVEL_ENTITY_DESCRIPTION, ToyotaSensor, None,`

I can confim this workaround helps. Restart of HA is required to apply changes.

**Comment by joost11111** [comment]
> > this is a workaround for anyone interested in updating HA core to the latest available release, while keeping the fuel level sensor enabled. I have updated line 230 in /homeassistant/custom_components/toyota/sensor.py file (replace PERCENTAGE with None) Now the fuel level is working but obviously no unit of measurement is assigned to the sensor. I am not a programmer, so this is just a workaround until this is resolved by the ha_toyota integration devs.
> > `vehicle._vehicle_info.extended_capabilities.fuel_level_available, FUEL_LEVEL_ENTITY_DESCRIPTION, ToyotaSensor, None,`
> 
> I can confim this workaround helps. Restart of HA is required to apply changes.

I did the workaround and it works but indeed without the percentage and just only a value. Thanks for now and hope there will be an update to reslove this.
![Capture](https://github.com/user-attachments/assets/edd9fbf5-425c-4967-b340-1c77bec1e9ca)

**Comment by mario-pranjic** [comment]
Any chance this getting resolved without manual workaround in sensor.py file?

**Comment by CM000n** [comment]
> suggest an incorrect unit of measurement

Feel free to open a Pull request for it.

It looks like Home Assistant has changed the restrictions for the `homeassistant.const` entries in one of its last versions, so that the `PERCENTAGE` entries can no longer be used freely.

Another option would be to change the `device_class` to a valid `SensorDeviceClass` for `PERCENTAGE` measuring units. For example, `SensorDeviceClass.BATTERY`. But as a result, the fuel level in Homeassistant would be displayed as a battery.

A better device_class would actually be `SensorDeviceClass.VOLUME_STORAGE`. However, only measurement units such as `mL`, `L`, `m³` are permitted for these.

**Comment by nisu66** [comment]
> > > this is a workaround for anyone interested in updating HA core to the latest available release, while keeping the fuel level sensor enabled. I have updated line 230 in /homeassistant/custom_components/toyota/sensor.py file (replace PERCENTAGE with None) Now the fuel level is working but obviously no unit of measurement is assigned to the sensor. I am not a programmer, so this is just a workaround until this is resolved by the ha_toyota integration devs.
> > > `vehicle._vehicle_info.extended_capabilities.fuel_level_available, FUEL_LEVEL_ENTITY_DESCRIPTION, ToyotaSensor, None,`
> > 
> > 
> > I can confim this workaround helps. Restart of HA is required to apply changes.
> 
> I did the workaround and it works but without the percentage and just only a value. Thanks for now and hope there will be an update to resolve this. ![Capture](https://private-user-images.githubusercontent.com/163320013/352779271-edd9fbf5-425c-4967-b340-1c77bec1e9ca.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDQxMzYsIm5iZiI6MTcyMzcwMzgzNiwicGF0aCI6Ii8xNjMzMjAwMTMvMzUyNzc5MjcxLWVkZDlmYmY1LTQyNWMtNDk2Ny1iMzQwLTFjNzdiZWMxZTljYS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNjM3MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTZmMDJiY2IzYzdmZmE0NjJiZTA2M2IwYjhhM2QyYTcxOTQ2MjA1ODJjYjQ3MTNlMDI2NTEzMDlmNDIwNzMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UMUWMuaA-drFKExnqgQQ0Tmdsuf1rB0pbY6JSX48VPc)

to get around the % problem, I used a solution, not beautiful but functional

**Comment by nisu66** [comment]
to get around the % problem, I used a solution, not beautiful but functional

 sensor:
  - platform: template
    sensors:
      percentuale_valore:
        friendly_name: "Percentuale Valore"
        unit_of_measurement: '%'
        value_template: >
          {{ (states('sensor.nameyuorsensor)|float)|round(2) }}

**Comment by tommeijering** [comment]
Other solution to add % sign:

Edit configuration.yaml
below line homeassistant: add line customize:

homeassistant:
  customize:
    **nameoffyoursensor**:
      unit_of_measurement: "%"

    **nameoffyoursensor** something like sensor.xxx_fuel_level

Don't forget : signs 

Check and reload configuration.yaml

**Comment by ajain-93** [comment]
I got it working by commenting out https://github.com/DurgNomis-drol/ha_toyota/blob/master/custom_components/toyota/sensor.py#L321.

I have looked around at the documentation, but am not really able to understand the difference between the `native_unit_of_measurement` and `suggested_unit_of_measurement` attributes.

**Comment by ajain-93** [comment]
Should be fixed now in `2.0.5` by #292.

**Comment by CM000n** [comment]
Closed due to discontinuation of the project. See: https://github.com/DurgNomis-drol/ha_toyota/issues/346
