### ISSUE TITLE
Detected blocking call to load_verify_locations with args

### ISSUE THREAD

**Issue by ricfio** [DurgNomis-drol/ha_toyota#308]
I can see an error in the log:

```
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f21ec6c6e50>,) inside the event loop by custom integration 'toyota' at custom_components/toyota/__init__.py, line 77: vehicles = await asyncio.wait_for(client.get_vehicles(metric=metric_values), 15) (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/DurgNomis-drol/ha_toyota/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/toyota/__init__.py", line 135, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 309, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 382, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 279, in _async_update_data return await self.update_method() File "/config/custom_components/toyota/__init__.py", line 77, in async_get_vehicle_data vehicles = await asyncio.wait_for(client.get_vehicles(metric=metric_values), 15)
```

**Comment by CM000n** [comment]
Duplicate of https://github.com/DurgNomis-drol/ha_toyota/issues/307

**Comment by skgsergio** [comment]
@CM000n This is not the same blocking call regarding `open()`, this one is due to this: https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations

The lib should allow passing a custom `httpx.AsyncClient` something like:

```python
from homeassistant.helpers.httpx_client import get_async_client

# ...

    client = MyT(..., httpx_client=get_async_client(hass))

# ...
```

And then the lib should use that client for performing the requests.
