### ISSUE TITLE
Many entities missing

### ISSUE THREAD

**Issue by fliespl** [DurgNomis-drol/ha_toyota#320]
**Describe the bug**
Screenshots explain it better/

**To Reproduce**
Just check listed entities.

**Expected behavior**
Entities available.

**Screenshots**
https://ss.codeone.pl/ss-2024-12-28-21-12-12-1735416732-NyrDuemM.png
https://ss.codeone.pl/ss-2024-12-28-21-13-48-1735416828-6E8tQLBz.png

**Additional context**

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/toyota/entity.py", line 53, in _handle_coordinator_update
    super()._handle_coordinator_update()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 294, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/toyota/binary_sensor.py", line 318, in is_on
    return self.entity_description.value_fn(self.vehicle)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/toyota/binary_sensor.py", line 60, in <lambda>
    value_fn=lambda vehicle: not vehicle.lock_status.doors.driver_seat.locked,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'driver_seat'
```

Sample error.

```
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 294, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/toyota/binary_sensor.py", line 318, in is_on
    return self.entity_description.value_fn(self.vehicle)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/toyota/binary_sensor.py", line 180, in <lambda>
    value_fn=lambda vehicle: not vehicle.lock_status.doors.passenger_rear_seat.closed,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by emilleszczak2** [comment]
I have the same error since yesterday. There was not update, I use 2.0.6 for long time.

**Comment by CM000n** [comment]
Closed due to discontinuation of the project. See: https://github.com/DurgNomis-drol/ha_toyota/issues/346
