### ISSUE TITLE
Fuel tank and Numberplate entity broken

### ISSUE THREAD

**Issue by Jozziej** [DurgNomis-drol/ha_toyota#36]
**Describe the bug**
The update to 1.0.1 breaks the Fuel tank and Numberplate entity

**To Reproduce**
Update from 1.0.0 to 1.0.1

**Logfile**
Logger: homeassistant.components.sensor
Source: custom_components/toyota/sensor.py:135
Integration: Sensor (documentation, issues)
First occurred: 23:05:37 (3 occurrences)
Last logged: 23:05:40

Error adding entities for domain sensor with platform toyota
Error while setting up toyota platform for sensor
toyota: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/config/custom_components/toyota/sensor.py", line 135, in state
    return self.coordinator.data[self.index][STATUS].odometer.fuel
TypeError: 'Vehicle' object is not subscriptable

**Comment by DurgNomis-drol** [comment]
Thanks for reporting this issue! I can see this is a typo from my side and I will push a fix shortly! 🎉

**Comment by DurgNomis-drol** [comment]
Can you please try to install master and post back your result? 😃

**Comment by Jozziej** [comment]
> Can you please try to install master and post back your result? 😃

Installed the Master and fixed it again

**Comment by DurgNomis-drol** [comment]
Great! 🎉 Thanks for testing
