### ISSUE TITLE
New version with newer binary sensors failed with message AttributeError: 'NoneType' object has no attribute 'passengerseat'

### ISSUE THREAD

**Issue by alexmihaila64** [DurgNomis-drol/ha_toyota#53]
**Describe the bug**
New version with newer binary sensors failed with message
AttributeError: 'NoneType' object has no attribute 'passengerseat'

**To Reproduce**
Initiating costom component after upgrade to latest version failed with message 
previos version without binary sensors worked ok.

**Expected behavior**
Finish initialization as previous version.

**Screenshots**
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/toyota/binary_sensor.py:72
Integration: Toyota Connected Services (documentation, issues)
First occurred: 6:30:55 PM (7 occurrences)
Last logged: 6:40:07 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 464, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 178, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/toyota/binary_sensor.py", line 72, in is_on
    window = getattr(
AttributeError: 'NoneType' object has no attribute 'passengerseat'

**Additional context**

**Comment by alexmihaila64** [comment]
ver 1.1.3 corrected that; thanks
