### ISSUE TITLE
Integration stop working after host machine restart 

### ISSUE THREAD

**Issue by daha76** [DurgNomis-drol/ha_toyota#69]
**Describe the bug**
I use HA on RPi and when I restart RPi then the integration isn't working anymore. I have to delete integration and add it again. Then the integration work until next restart.

**To Reproduce**
1. Restart RPi via 'sudo reboot'
2. Check integration status in HA configuration

**Expected behavior**
I would expect that the integration will work also after restart.

**Log findinfs**
`2021-09-20 15:45:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry daniel.hajduch@gmail.com for toyota
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 61, in map_httpcore_exceptions
yield
File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 281, in handle_async_request
) = await self._pool.handle_async_request(
File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
response = await connection.handle_async_request(
File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 136, in handle_async_request
self.socket = await self._open_socket(timeout)
File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 163, in _open_socket
return await self._backend.open_tcp_stream(
File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 44, in open_tcp_stream
return await self.backend.open_tcp_stream(
File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 154, in open_tcp_stream
stream = await TLSStream.wrap(
File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
self.gen.throw(typ, value, traceback)
File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
raise to_exc(exc) from None
httpcore.ConnectTimeout
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/toyota/__init__.py", line 69, in async_setup_entry
await client.login()
File "/usr/local/lib/python3.9/site-packages/mytoyota/client.py", line 81, in login
await self.api.controller.first_login()
File "/usr/local/lib/python3.9/site-packages/mytoyota/controller.py", line 70, in first_login
await self._update_token()
File "/usr/local/lib/python3.9/site-packages/mytoyota/controller.py", line 83, in _update_token
response = await client.post(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1825, in post
return await self.request(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
response = await self.send(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
response = await self._send_handling_auth(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
response = await self._send_handling_redirects(
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
response = await self._send_single_request(request, timeout)
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
) = await transport.handle_async_request(
File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 276, in handle_async_request
(
File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
self.gen.throw(typ, value, traceback)
File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 78, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ConnectTimeout`

**Comment by DurgNomis-drol** [comment]
I can't replicate the issue, though you are not the only who have posted this bug. 

It seems to be caused by Toyota's servers not responding when the first update is called after a restart and those it cannot setup the config entry. 

I will look into it

**Comment by DurgNomis-drol** [comment]
I believe I have fixed it now, though i haven been able to test it. Please update to `1.2.3` and report back!

If the issue persist, don't hesitate to open this again 😃

**Comment by daha76** [comment]
Thanks. I tested it and so far so good, thanks ;-)
