### ISSUE TITLE
Impossible to fetch data when multiple cars

### ISSUE THREAD

**Issue by mrblur** [DurgNomis-drol/ha_toyota#74]
**Describe the bug**
Since lates update, it is impossible to fetch any data as the component is constantly failing.
I'm assuming, this is due to my account having two cars, one without the connectivity.

**To Reproduce**

1. Have two cars linked to your account
2. One without connectivity (Aygo '2019)
3. On with connectivity (Corolla '2020)
4. See errors

```
2021-10-20 18:38:00 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (None). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-10-20 18:38:00 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
```

**Expected behavior**
I'd love to see the component running again, ignoring the errors about car being unsupported and refresh the entities that are supported. I really do not want to unlink the aygo from my account as it helps me keeping servicing on schedule.

**Screenshots**

**Additional context**

**Comment by DurgNomis-drol** [comment]
Thanks for reporting this issue 😊

Just be sure, the Aygo does not support MyT in anyway? I am double checking because mine does (Aygo 2020/2021 model). 

If it does not then we need to implement a fix for it as it should obviously work even when only one car supports MyT 😊

**Comment by mrblur** [comment]
Well, I do have Aygo listed on MyT, that's why it is registered on the account.
But the car does not have connectivity (no modem, navi, no track records, odometer or fuel reported like for corolla).

Some time before 1.2.3 my Home-Assistant fetched its data (only license plate entity) just fine, but after latest release I have no data at all.

**Comment by DurgNomis-drol** [comment]
Update: Can you please try to install the latest `master`, it should contain a fix for your problem. Please test it and report back if it works or not. 😃

Be aware that this also contains some new features that have not been released before and those not tested very thoroughly yet!

**Comment by mrblur** [comment]
I'll come back to you as soon as I test it out. Currently at toyota, doing yearly service on the aygo. Nice timing ;)

**Comment by mrblur** [comment]
Fetched the master, unpacked, restarted HA.

```
2021-11-06 15:54:57 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-11-06 15:54:57 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
2021-11-06 15:54:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 67, in _initialize
    await watcher.async_start()
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 225, in async_start
    self._async_process_device_state(state)
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 250, in _async_process_device_state
    self.async_process_client(ip_address, hostname, _format_mac(mac_address))
  File "/usr/src/homeassistant/homeassistant/components/dhcp/__init__.py", line 104, in async_process_client
    made_ip_address = make_ip_address(ip_address)
  File "/usr/local/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'static-personal' does not appear to be an IPv4 or IPv6 address
2021-11-06 15:55:20 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-11-06 15:55:20 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
2021-11-06 15:55:45 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-11-06 15:55:45 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
2021-11-06 15:56:31 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-11-06 15:56:31 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
```

Verified that the docker pulled mytoyota 0.7.3.

Still no luck.
Neither of the cars is available.

Removed the integration, and configured from scratch:

```
2021-11-06 16:10:23 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-11-06 16:10:23 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
2021-11-06 16:10:23 WARNING (MainThread) [homeassistant.config_entries] Config entry '***EDITED***' for toyota integration not ready yet: None; Retrying in background
2021-11-06 16:10:34 ERROR (MainThread) [mytoyota] Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.
2021-11-06 16:10:34 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 'NoneType' object has no attribute 'unit'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/toyota/__init__.py", line 90, in async_update_data
    if vehicle.odometer.unit == LENGTH_MILES:
AttributeError: 'NoneType' object has no attribute 'unit'
```

**Comment by DurgNomis-drol** [comment]
Thanks for the feedback! I can see that I missed something and have just pushed a new fix that should address that. Can you try again with the latest master? 😃

**Comment by mrblur** [comment]
Tested again and.. it worked!

Got numberplate entity for Aygo, and everything else for Corolla!

Altough, there is this warnig in the logs  repeating in time:

`Your vehicle does not support Connected services (). You can find out if your vehicle is compatible by checking the manual that comes with your car.`

It should have the car name or license plate at least ;) Some identifier. I see the log repeating, that's not perfect, but I can live with that :+1: 

Anyway,

Thank you for your fix!

**Comment by DurgNomis-drol** [comment]
Great to hear! Either i will change it to a warning or find a way to only show it once in startup 😊
